server:
  port: 8873
spring:
  application:
    name: discovery
  config:
    import: optional:configserver:http://config-user:config-password@localhost:8869/
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"